### ISSUE TITLE
Change from FirstOrDefaultAsync to SingleOrDefaultAsync or express both in separated methods

### ISSUE THREAD

**Issue by luizcarlosfaria** [guilhermecaixeta/Generic.Repository.RichDomain.DotNetCore2.2#1]
https://github.com/guilhermecaixeta/Generic.Repository.RichDomain.DotNetCore2.2/blob/65cf6823a776a3ec8d4a3c6f2f26356a462d0754/src/Generic.Repository/Repository/IBaseRepository/BaseRepository/BaseRepository.cs#L43

**Comment by guilhermecaixeta** [comment]
Done!
