### ISSUE TITLE
AsNoTracking is not a decision for any Library, is a developer decision

### ISSUE THREAD

**Issue by luizcarlosfaria** [guilhermecaixeta/Generic.Repository.RichDomain.DotNetCore2.2#3]
https://github.com/guilhermecaixeta/Generic.Repository.RichDomain.DotNetCore2.2/blob/65cf6823a776a3ec8d4a3c6f2f26356a462d0754/src/Generic.Repository/Repository/IBaseRepository/BaseRepository/BaseRepository.cs#L35

> Docs about AsNoTracking 
> 
> Returns a new query where the change tracker will not track any of the entities that are returned. 
> If the entity instances are modified, this will not be detected by the change tracker and Microsoft.EntityFrameworkCore.DbContext.SaveChanges
> will not persist those changes to the database. 
> 
> Disabling change tracking is useful for read-only scenarios because it avoids the overhead of setting up change tracking for each entity instance. 
> You should not disable change tracking if you want to manipulate entity instances and persist those changes to the database using Microsoft.EntityFrameworkCore.DbContext.SaveChanges.
> 
> Identity resolution will still be performed to ensure that all occurrences of an entity with a given key in the result set are represented by the same entity instance. 
> 
> The default tracking behavior for queries can be controlled by Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.QueryTrackingBehavior.
>

**Comment by guilhermecaixeta** [comment]
I gived the options to developer choose if be use AsNoTracking or not. Check it.

**Comment by guilhermecaixeta** [comment]
Done!
