### ISSUE TITLE
Reflection without Cache - GetType().GetProperty(Order) is used for every row

### ISSUE THREAD

**Issue by luizcarlosfaria** [guilhermecaixeta/Generic.Repository.RichDomain.DotNetCore2.2#6]
https://github.com/guilhermecaixeta/Generic.Repository.RichDomain.DotNetCore2.2/blob/65cf6823a776a3ec8d4a3c6f2f26356a462d0754/src/Generic.Repository/Models/BaseEntities/BasePagination/BasePagination.cs#L53#L54

**Comment by guilhermecaixeta** [comment]
Done!
